apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-demo-servicemonitor
  namespace: platform-demo
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: platform-demo
  namespaceSelector:
    matchNames:
      - platform-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
